Mission4WebApp/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4WebApp.Models
{
    public class GradeCalculatorModel
    {
        //sets up data validation for fields to be required and within 0-100
        public string output { get; set; }

        [Required]
        [Range(0,100.00)]
        public float assignment { get; set; }

        [Required]
        [Range(0, 100.00)]
        public float quiz { get; set; }

        [Required]
        [Range(0, 100.00)]
        public float group { get; set; }

        [Required]
        [Range(0, 100.00)]
        public float intex { get; set; }

        [Required]
        [Range(0, 100.00)]
        public float midterm { get; set; }

        [Required]
        [Range(0, 100.00)]
        public float final { get; set; }
    }
}

Mission4WebApp/Controllers/BasicController.cs
using Microsoft.AspNetCore.Mvc;
using Mission4WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4WebApp.Controllers
{
    public class BasicController : Controller
    {
        public IActionResult Index ()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator ()
        {
            return View();
        }


        [HttpPost]
        public IActionResult GradeCalculator (GradeCalculatorModel model)
        {
            return View();
        }
    }
}

Mission4WebApp/Views/Basic/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model GradeCalculatorModel;

<h3>Final Grade Calculator:</h3>

<!--Set up the inputs for the jquery-->
<form method="post">
    <h5>Final Grade:</h5>
    <p id="output" name="output"></p>

    <label>Assignments Grade (%):</label>
    <input id="assignment" asp-for="assignment" /><br />

    <label>Quizzes Grade (%):</label>
    <input id="quiz" asp-for="quiz" /><br />

    <label>Group Projects Grade (%):</label>
    <input id="group" asp-for="group"/><br />

    <label>INTEX Grade (%):</label>
    <input id="intex" asp-for="intex"/><br />

    <label>Midterm Exam Grade (%):</label>
    <input id="midterm" asp-for="midterm"/><br />

    <label>Final Exam Grade (%):</label>
    <input id="final" asp-for="final"/><br />

    <input id="send" type="submit" value="Calculate Grade" />

    @*allows data validation to be used*@
    <div asp-validation-summary="All"></div>
</form>

<script src="js/GradeCalculator.js"></script>

Mission4WebApp/Views/Basic/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Jacob's House";
}


<h1>Jacob Sargent</h1>
<img src="img/jacobRun.jpg" />
<br />
<br />
<p>
    In IS 413 I hope to be able to learn how to make webapps better because Django was great but pretty darn
    complicated. I am also excited to learn how to use React. Overall, I would just like to come out of this
    class being more comfortable with programing.
</p>
<h3>The Top 3 Jobs I would like to Pursue:</h3>
<ol>
    <li>Project Manager</li>
    <li>Developer</li>
    <li>Consultant</li>
</ol>

Mission4WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
@*brings in the favicon and styling and data using razor code for every page*@
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="img/Smiley.svg.png">
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <link href="lib/bootstrap/bootstrap-5.3.0-alpha1-dist/css/bootstrap.min.css" rel="stylesheet" />
</head>

@*Sets up nav bar*@
<body>

    <nav>
        <a asp-controller="Basic" asp-action="Index">Home</a>
        <a asp-controller="Basic" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <script src="lib/bootstrap/bootstrap-5.3.0-alpha1-dist/js/bootstrap.min.js"></script>
    <script src="lib/jquery/jquery-3.6.3.min.js"></script>

</body>

</html>